version: '3'

services:
  sabnzbd:
    image: sabnzbd/sabnzbd
    networks:
      - traefik-net
      - default
    environment:
      - SABNZBD_UID=0
      - SABNZBD_GID=0
    volumes:
      - snzb_datadir:/datadir
      - snzb_media:/media
    deploy:
      labels:
        - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
        - "traefik.http.routers.sabnzbd.rule=Host(`downloads.bluehairfreak.com`)"
        - "traefik.http.routers.sabnzbd.entrypoints=http"
        - "traefik.enable=true"

  sonarr:
    image: linuxserver/sonarr
    networks:
      - traefik-net
      - default
    environment:
      - PUID=0
      - GUID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr_config:/config
      - sonarr_tv:/tv
      - media:/downloads
    deploy:
      labels:
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        - "traefik.http.routers.sonarr.rule=Host(`tv.bluehairfreak.com`)"
        - "traefik.http.routers.sonarr.entrypoints=http"
        - "traefik.enable=true"

  plex:
    image: plexinc/pms-docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-xqKmgVRCibq8NytWFF3F
      - ADVERTISE_IP=http://192.168.0.12:32400
      - PLEX_UID=0
      - PLEX_GID=0
    volumes:
      - plex_config:/config
      - sonarr_tv:/data/tvshows
      - radarr_movies:/data/movies
    deploy:
      placement:
        constraints: [node.hostname == node2.bluehairfreak.com]

  radarr:
    image: linuxserver/radarr
    networks:
      - traefik-net
      - default
    environment:
      - GUID=0
      - PUID=0
    volumes:
      - radarr_movies:/movies
      - radarr_config:/config
      - media:/downloads
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        - "traefik.http.routers.radarr.rule=Host(`movies.bluehairfreak.com`)"
        - "traefik.http.routers.radarr.entrypoints=http"
        - "traefik.enable=true"

volumes:
  snzb_datadir:
    driver: rexray/scaleio
    driver_opts:
      size: 50
  sonarr_config:
    driver: rexray/scaleio
    driver_opts:
      size: 50
  radarr_config:
    driver: rexray/scaleio
    driver_opts:
      size: 50
  plex_config:
    driver: rexray/scaleio
    driver_opts:
      size: 50
  snzb_media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=node2.bluehairfreak.com,rw,nolock,vers=4,hard
      device: ":/sabnzbd"
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=node2.bluehairfreak.com,rw,nolock,vers=4,hard
      device: ":/"
  sonarr_tv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=node2.bluehairfreak.com,rw,nolock,vers=4,hard
      device: ":/tv"
  radarr_movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=node2.bluehairfreak.com,rw,nolock,vers=4,hard
      device: ":/movies"

networks:
  traefik-net:
    external: true
